version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
